### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#409]
## Version 1.0.0

- [ ] **breaking**: performance improvements, this could include the major architecture change
- [x] **breaking**: complete refactoring of the violations order, codes, and modules
- [x] **breaking**: new violation type: `patterns`, which will include violations that are raised when we find different bad patterns inside the codebase: like `yield` in `__init__` or `else` without `break` in a loop, etc
- [ ] zero config setup, related #164 
- [x] configuration validation, related #127 
- [x] verbose output with solutions and links to our online docs

## Version pre-1.0

- [ ] `python3.8` support

## Version 0.10

- [x] new features from the backlog: dynamic complexity, overused expressions and strings, new checks

## Version 0.9

- [x] regressions, bugs, refactoring, etc

## Version 0.8

- [x] regressions, bugs, refactoring, etc
- [x] just some new rules: brackets, some other complex stuff

## Version 0.7

- [x] regressions, bugs, refactoring, etc
- [x] just some new rules, list of tasks is here: https://github.com/wemake-services/wemake-python-styleguide/milestone/5

**Comment by sobolevn** [comment]
We also need to adapt to `python3.8`.
It has a completely different `ast`.

So, I guess we will need to create a compatibility layer.

**Comment by sobolevn** [comment]
Version `0.9.0` is here: https://github.com/wemake-services/wemake-python-styleguide/releases/tag/0.9.0 🎉 🎉 🎉

**Comment by AlwxSin** [comment]
@sobolevn how about using [github projects](https://github.com/wemake-services/wemake-python-styleguide/projects) instead of this issue?

**Comment by sobolevn** [comment]
Closed, we now use milestones.
