### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/wemake-python-styleguide#60]
# Roadmap

In this issue I would like to discuss the future of the project.
And I invite to collaborate all contributors.
@malinoff @proha @barsovichok @vergeev @mcproger @lk-geimfari 

## Current tasks

I see several group of tasks to be completed before the project can be publicly released:
1. Documentation
2. New rules
3. Testing, providing new examples, different usecases and testing strategies

Currently I feel like we should concentrate on writing new rules.
Because we can already use them and gain some productivity in return.

### Documentation

The main issue to be solved here is reasoning. We need to write why you should write `A` and should not write `B`. 

We also need examples, references, and refactoring guides.

### Rule related tasks

There are several kind of tasks to be handled:
1. `ast`-based rules
2. `tokenize`-based rules

While we already have several `ast`-based checkers implemented, there are currently no examples of 2 group rules. 

We can not check for things like `u'abc'` with `ast`, we need to use `tokenize`.

## Milestones

I believe that setting a first `0.1.0` release milestone at somewhere near November is pretty realistic. 

Before releasing `0.1.0` we need to be sure that we have:

- [x] error numbers that won't be changed (currently they change a lot)
- [x] rules that check classes for number of methods
- [x] complexity rules: branching and nesting
- [x] rules that check strings for `u`, `f`, and others
- [x] rules that check modules and functions for length
- [x] rules that check comments
- [x] `jones-complexity` integrated (I am still not able to publish the latest version)
- [x] documentation about each rule, why we have it, why our solution is the best one
- [x] documentation about how to use this plugin with other `flake8` plugins, what is the recommended list

For next releases we can plan to add other features like:
- `django` support
- `celery` support
- `async` specific rules (I do not use `async` personally)

**Comment by sobolevn** [comment]
There's an option to use https://github.com/PyCQA/baron instead of `tokenize` and `ast`.
It need some further investigation.

I don't want to rewrite the existing rules, but maybe we can just use it sometimes.
Things to keep in mind:
- is it possible to easily integrate it to `flake8` plugin?
- speed, I am pretty sure that `ast` and `tokenize` is faster than `baron`. We need to know how much faster
- `baron` vs `redbaron` stuff

**Comment by malinoff** [comment]
> The main issue to be solved here is reasoning. We need to write why you should write A and should not write B.

I skimmed the readme and I couldn't find a word about why would I use this plugin. I mean not a thorough descriptions about decisions made, but decisions themselves.

**Comment by sobolevn** [comment]
Yeap, `README` does not reflect these things yet. There some pieces of information that is shattered across original issues.

But some rules/decisions/etc are just not covered at all.

**Comment by sobolevn** [comment]
We are almost ready for the first public release. Only these two issues are standing in the way:
- https://github.com/wemake-services/wemake-python-styleguide/issues/131
- https://github.com/wemake-services/wemake-python-styleguide/issues/114

Closing this roadmap. Thanks everyone!
